<?php

namespace AppBundle\Repository;

/**
 * ArmorHullRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmorHullRepository extends \Doctrine\ORM\EntityRepository
{
}
