<?php

namespace AppBundle\Repository;

/**
 * ArmorTurretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmorTurretRepository extends \Doctrine\ORM\EntityRepository
{
}
