<?php

namespace AppBundle\Repository;

/**
 * GunPerformanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GunPerformanceRepository extends \Doctrine\ORM\EntityRepository
{
}
