<?php

namespace AppBundle\Repository;

/**
 * GunRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GunRepository extends \Doctrine\ORM\EntityRepository
{
}
