<?php

namespace AppBundle\Repository;

/**
 * VehicleTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
