# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        main:
            entity: { class: AppBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                csrf_token_generator: security.csrf.token_manager
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /

    encoders:
        AppBundle\Entity\User: sha512

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
