# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        main:
            entity: { class: AppBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

    encoders:
        AppBundle\Entity\User: sha512
