services:
    slugger:
        class: 'AppBundle\Services\SluggerService'

    file_uploader:
        class: 'AppBundle\Services\FileUploaderService'
        arguments:
            - '%uploads_directory%'

    fixture_loader:
        class: 'AppBundle\Services\FixturesLoaderService'

    image_upload_listener:
        class: 'AppBundle\EventListener\ImageUploadListener'
        arguments:
            - '@file_uploader'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    slugger_listener:
        class: 'AppBundle\EventListener\SluggerListener'
        arguments:
            - '@slugger'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    admin.vendor:
        class: AppBundle\Admin\VendorAdmin
        arguments: [~, AppBundle\Entity\Vendor, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Vendors }
        public: true

    admin.vehicle_type:
        class: AppBundle\Admin\VehicleTypeAdmin
        arguments: [~, AppBundle\Entity\VehicleType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Vehicle Types }
        public: true

    admin.tank:
        class: AppBundle\Admin\TankAdmin
        arguments: [~, AppBundle\Entity\Tank, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Tanks }
        public: true

    admin.size:
            class: AppBundle\Admin\SizeAdmin
            arguments: [~, AppBundle\Entity\Size, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Sizes }
            public: true

    admin.gun:
            class: AppBundle\Admin\GunAdmin
            arguments: [~, AppBundle\Entity\Gun, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Guns }
            public: true

    admin.engine:
            class: AppBundle\Admin\EngineAdmin
            arguments: [~, AppBundle\Entity\Engine, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Engines }
            public: true

    admin.shell:
            class: AppBundle\Admin\ShellAdmin
            arguments: [~, AppBundle\Entity\Shell, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Shells }
            public: true
