services:
    file_uploader:
        class: 'AppBundle\Services\FileUploaderService'
        arguments:
            - '%uploads_directory%'
    image_upload_listener:
        class: 'AppBundle\EventListener\ImageUploadListener'
        arguments:
            - '@file_uploader'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    admin.vendor:
        class: AppBundle\Admin\VendorAdmin
        arguments: [~, AppBundle\Entity\Vendor, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Vendors }
        public: true
    admin.vehicle_type:
        class: AppBundle\Admin\VehicleTypeAdmin
        arguments: [~, AppBundle\Entity\VehicleType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Vehicle Types }
        public: true
    admin.tank:
        class: AppBundle\Admin\TankAdmin
        arguments: [~, AppBundle\Entity\Tank, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Tanks }
        public: true
